/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ChatRouteImport } from "./routes/chat";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as UsersIndexRouteImport } from "./routes/users/index";
import { Route as UsersUsernameRouteImport } from "./routes/users/$username";

const ChatRoute = ChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: "/users/",
  path: "/users/",
  getParentRoute: () => rootRouteImport,
} as any);
const UsersUsernameRoute = UsersUsernameRouteImport.update({
  id: "/users/$username",
  path: "/users/$username",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/chat": typeof ChatRoute;
  "/todo/$todoid": typeof TodoTodoidRoute;
  "/todo": typeof TodoIndexRoute;
  "/users/$username": typeof UsersUsernameRoute;
  "/users": typeof UsersIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/users/$username": typeof UsersUsernameRoute;
  "/users": typeof UsersIndexRoute;
  "/chat": typeof ChatRoute;
  "/todo/$todoid": typeof TodoTodoidRoute;
  "/todo": typeof TodoIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/users/$username": typeof UsersUsernameRoute;
  "/users/": typeof UsersIndexRoute;
  "/chat": typeof ChatRoute;
  "/todo/$todoid": typeof TodoTodoidRoute;
  "/todo/": typeof TodoIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/about" | "/users/$username" | "/users";
  fullPaths: "/" | "/about" | "/chat" | "/todo/$todoid" | "/todo";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/about" | "/users/$username" | "/users";
  id: "__root__" | "/" | "/about" | "/users/$username" | "/users/";
  to: "/" | "/about" | "/chat" | "/todo/$todoid" | "/todo";
  id: "__root__" | "/" | "/about" | "/chat" | "/todo/$todoid" | "/todo/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  UsersUsernameRoute: typeof UsersUsernameRoute;
  UsersIndexRoute: typeof UsersIndexRoute;
  ChatRoute: typeof ChatRoute;
  TodoTodoidRoute: typeof TodoTodoidRoute;
  TodoIndexRoute: typeof TodoIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/chat": {
      id: "/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof ChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/users/": {
      id: "/users/";
      path: "/users";
      fullPath: "/users";
      preLoaderRoute: typeof UsersIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/users/$username": {
      id: "/users/$username";
      path: "/users/$username";
      fullPath: "/users/$username";
      preLoaderRoute: typeof UsersUsernameRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  UsersUsernameRoute: UsersUsernameRoute,
  UsersIndexRoute: UsersIndexRoute,
  ChatRoute: ChatRoute,
  TodoTodoidRoute: TodoTodoidRoute,
  TodoIndexRoute: TodoIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
